### ISSUE TITLE
Cannot read property 

### ISSUE THREAD

**Issue by maxou45400** [AuspeXeu/openvpn-status#395]
Hello,
When a user connects to my VPN, in the logs in PM2, I end up with the following errors. I want to point out that I’m on a debian 10.

![image](https://user-images.githubusercontent.com/35854041/72730146-0cd7fe00-3b91-11ea-984b-2cfa50943bd9.png)

So I would need your help to understand the problem

Good Day, 
Cordially, 
Maxou45400

**Comment by AuspeXeu** [comment]
What version are you using?

**Comment by maxou45400** [comment]
4.2.24

**Comment by clementdebette** [comment]
/root/.pm2/logs/openvpn-status-error.log last 15 lines:
0|openvpn- | TypeError: Cannot read property 'Client ID' of undefined
0|openvpn- |     at mkClient (/etc/openvpn-status/openvpn-status/openvpn.js:5:14)
0|openvpn- |     at getClients.then (/etc/openvpn-status/openvpn-status/openvpn.js:100:39)
0|openvpn- |     at process._tickCallback (internal/process/next_tick.js:68:7)
0|openvpn- | TypeError: Cannot read property 'Client ID' of undefined
0|openvpn- |     at mkClient (/etc/openvpn-status/openvpn-status/openvpn.js:5:14)
0|openvpn- |     at getClients.then (/etc/openvpn-status/openvpn-status/openvpn.js:100:39)
0|openvpn- |     at process._tickCallback (internal/process/next_tick.js:68:7)
0|openvpn- | TypeError: Cannot read property 'Client ID' of undefined
0|openvpn- |     at mkClient (/etc/openvpn-status/openvpn-status/openvpn.js:5:14)
0|openvpn- |     at getClients.then (/etc/openvpn-status/openvpn-status/openvpn.js:100:39)
0|openvpn- |     at process._tickCallback (internal/process/next_tick.js:68:7)

Maybe I will try ton put my hand into openvpn.js and see.
See also a new package today about mp2 today.

**Comment by AuspeXeu** [comment]
Can you try with the new version? :)

**Comment by clementdebette** [comment]
Hello, 

Sorry I didn't see your mail, I wasn't looking this mail adress since a while. 
Everything works except the disconnection button for each clients. 
It send back an error on the browser like "post cannot access it". 

Regards, 
DEBETTE Clément 
----- Mail original -----

De: "Chris Vaas" <notifications@github.com> 
À: "AuspeXeu/openvpn-status" <openvpn-status@noreply.github.com> 
Cc: "clementdebette" <clement.debette@laposte.net>, "Comment" <comment@noreply.github.com> 
Envoyé: Vendredi 13 Mars 2020 23:48:37 
Objet: Re: [AuspeXeu/openvpn-status] Cannot read property (#395) 






Can you try with the new version? :)
